<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MqttForge.Application\MqttForge.Application.csproj" />
    <ProjectReference Include="..\MqttForge.Domain\MqttForge.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
